import { MenuItem, CategoryInfo } from './types';

export const RESTAURANT_INFO = {
  name: 'Al Aqsa Restaurant & Cafeteria',
  arabicName: 'مطعم ومقهى الأقصى',
  phone: '0551162600',
  formattedPhone: '+971 55 116 2600',
  coordinates: {
    lat: 25.1451125,
    lng: 55.4044960,
  },
  address: 'Warsan Fourth - International City Phase(2) - Dubai, UAE',
  arabicAddress: 'الورسان الرابعة - المدينة العالمية المرحلة (2) - دبي، الإمارات العربية المتحدة',
  hours: '8:00 AM - 12:00 AM (Daily)',
  arabicHours: '8:00 صباحاً - 12:00 منتصف الليل (يومياً)',
};

export const CATEGORIES: CategoryInfo[] = [
  {
    id: 'breakfast',
    name: 'Breakfast',
    arabicName: 'الفطور',
    icon: 'Coffee',
    description: 'Traditional morning delicacies and egg platters to start your day.',
  },
  {
    id: 'specials',
    name: 'Al Aqsa Specials',
    arabicName: 'ميزات الأقصى',
    icon: 'Sparkles',
    description: 'Our signature house-crafted special dishes made from legacy recipes.',
  },
  {
    id: 'grilled',
    name: 'Al Aqsa Grilled',
    arabicName: 'مشاوي الأقصى',
    icon: 'Flame',
    description: 'Premium charcoal-grilled meats, kebabs, tikkas, and roasted chicken.',
  },
  {
    id: 'shawarma',
    name: 'Shawarma',
    arabicName: 'الشاورما',
    icon: 'ChefHat',
    description: 'Authentic sliced chicken & beef shawarmas, wraps, and combo meals.',
  },
  {
    id: 'sandwiches',
    name: 'Sandwiches',
    arabicName: 'السندويشات',
    icon: 'FolderHeart',
    description: 'Flavorful quick bites, signature falafel wraps, and premium burgers.',
  },
  {
    id: 'pastries',
    name: 'Pastries & Pizza',
    arabicName: 'المعجنات والبيتزا',
    icon: 'Cookie',
    description: 'Freshly baked Manakeesh flatbreads and hot oven pizzas.',
  },
  {
    id: 'plates',
    name: 'Main Plates',
    arabicName: 'الأطباق الرئيسية',
    icon: 'Utensils',
    description: 'Rich, authentic Arabic stews, kafta plates, and biryani.',
  },
  {
    id: 'appetizers',
    name: 'Appetizers & Hummus',
    arabicName: 'المقبلات والحمص',
    icon: 'Columns4',
    description: 'Perfect starters, fresh hummus variations, and dipping plates.',
  },
  {
    id: 'salads',
    name: 'Fresh Salads',
    arabicName: 'السلطات الطازجة',
    icon: 'Leaf',
    description: 'Crisp, refreshing, hand-chopped traditional Arab salads.',
  },
  {
    id: 'soups',
    name: 'Warm Soups',
    arabicName: 'الشوربات',
    icon: 'Soup',
    description: 'Comforting, nutrient-rich soups served with toasted bread.',
  },
  {
    id: 'beverages',
    name: 'Cold Beverages',
    arabicName: 'المشروبات الباردة',
    icon: 'GlassWater',
    description: 'Refreshing mineral waters, soft carbonated sodas, and fresh juices.',
  },
];

export const MENU_ITEMS: MenuItem[] = [
  // --- BREAKFAST ---
  {
    id: 'bk-grape-leaves',
    name: 'Grape Leaves (Breakfast size)',
    arabicName: 'ورق عنب فطور',
    price: 10,
    category: 'breakfast',
    description: 'Tender vine leaves stuffed with a savory rice, herb, and lemon mixture.',
    arabicDescription: 'ورق عنب محشي بالأرز المتبل والليمون وزيت الزيتون.',
  },
  {
    id: 'bk-french-fries',
    name: 'French Fries (Breakfast size)',
    arabicName: 'بطاطس مقلية فطور',
    price: 15,
    category: 'breakfast',
    description: 'Golden-crispy potato fries, lightly salted and served hot.',
    arabicDescription: 'أصابع البطاطس المقلية المقرمشة والذهبية.',
  },
  {
    id: 'bk-spicy-potatoes',
    name: 'Spicy Potatoes (Breakfast size)',
    arabicName: 'بطاطا حرة فطور',
    price: 10,
    category: 'breakfast',
    description: 'Cubes of crispy potato sautéed with garlic, fresh coriander, chili, and olive oil.',
    arabicDescription: 'مكعبات البطاطا المقلية ومحمرة مع الثوم والكزبرة الطازجة والفلفل الحار.',
    isSpicy: true,
  },
  {
    id: 'bk-fried-egg',
    name: 'Fried Egg Plate',
    arabicName: 'صحن بيض مقلي',
    price: 18,
    category: 'breakfast',
    description: 'Fresh farm eggs pan-fried to perfection with authentic Arabic spices.',
    arabicDescription: 'بيض طازج مقلي مع مسحة من البهارات اللطيفة.',
  },
  {
    id: 'bk-fried-egg-meat',
    name: 'Fried Egg Plate with Meat',
    arabicName: 'صحن بيض مقلي باللحمة',
    price: 14,
    category: 'breakfast',
    description: 'Scrambled or sunny side eggs cooked with spiced minced lamb and beef.',
    arabicDescription: 'بيض مقلي مطهو مع قطع اللحم المفروم المتبل.',
    isPopular: true,
  },
  {
    id: 'bk-fried-egg-cheese',
    name: 'Fried Egg Plate with Cheese',
    arabicName: 'صحن بيض مقلي بالجبنة',
    price: 25,
    category: 'breakfast',
    description: 'Pan-fried eggs folded with melted premium Halloumi/Akkawi cheese.',
    arabicDescription: 'بيض مقلي كريمي مغطى بطبقة غنية من قشقوان أو جبنة عكاوي ذائبة.',
  },
  {
    id: 'bk-chicken-liver',
    name: 'Chicken Liver Plate',
    arabicName: 'صحن كبدة دجاج فطور',
    price: 20,
    category: 'breakfast',
    description: 'Sautéed fresh chicken liver with onions, garlic, and a drizzle of pomegranate molasses.',
    arabicDescription: 'كبدة دجاج طازجة مطهوة مع البصل والثوم ودبس الرمان اللذيذ.',
  },
  {
    id: 'bk-mixed-veg',
    name: 'Mixed Fried Veg Plates',
    arabicName: 'صحن خضار مقلي مشكل فطور',
    price: 15,
    category: 'breakfast',
    description: 'Assortment of fried eggplant, cauliflower, and zucchini served with tahini sauce.',
    arabicDescription: 'تشكيلة من الباذنجان والزهرة والكوسا المقلية تقدم مع صلصة الطحينة.',
    isVegetarian: true,
  },
  {
    id: 'bk-mufaraka-egg',
    name: 'Mufaraka Potato with Eggs',
    arabicName: 'مفركة بطاطا بالبيض',
    price: 20,
    category: 'breakfast',
    description: 'Traditional Levant dish of diced potatoes cooked slowly with scrambled eggs and local ghee.',
    arabicDescription: 'طبق مفركة البطاطا التقليدي مطهو مع البيض المخفوق والبهارات.',
  },
  {
    id: 'bk-mufaraka-meat',
    name: 'Mufaraka Potato with Meat',
    arabicName: 'مفركة بطاطا باللحمة',
    price: 15,
    category: 'breakfast',
    description: 'Finely minced meat stewed with tender cubes of seasoned potato and onions.',
    arabicDescription: 'مكعبات البطاطا الطرية المطهوة مع اللحم المفروم والبهارات العربية.',
  },
  {
    id: 'bk-fried-tomato',
    name: 'Fried Tomato Plate',
    arabicName: 'قلاية بندورة بالثوم',
    price: 18,
    category: 'breakfast',
    description: 'Vine-ripened tomatoes sautéed under oil with chili, garlic, and pine nuts.',
    arabicDescription: 'طماطم ناضجة مطبوخة في المقلاة بزيت الزيتون مع الثوم والفلفل.',
    isVegetarian: true,
  },
  {
    id: 'bk-broad-beans-oil',
    name: 'Broad Beans with Olive Oil',
    arabicName: 'فول بالزيت الزيتون',
    price: 14,
    category: 'breakfast',
    description: 'Slow-simmered fava beans dressed with extra virgin olive oil, garlic, and cumin.',
    arabicDescription: 'فول مدمس مطبوخ ببطء ومتبل بخلطة الثوم والليمون وزيت الزيتون البكر.',
    isVegetarian: true,
  },
  {
    id: 'bk-broad-beans-tahinia',
    name: 'Broad Beans with Tahinia',
    arabicName: 'فول بالطحينة',
    price: 14,
    category: 'breakfast',
    description: 'Creamy fava beans blended with premium sesame paste (tahini), garlic, and herbs.',
    arabicDescription: 'فول مدمس ممزوج بالطحينة الممتازة وعصير الليمون والثوم.',
    isVegetarian: true,
  },
  {
    id: 'bk-meat-fatteh',
    name: 'Meat Fatteh (Breakfast)',
    arabicName: 'فتة لحمة فطور',
    price: 30,
    category: 'breakfast',
    description: 'Crisp pita chips, chickpea layers under garlic yogurt, warm ghee, and sautéed minced meat.',
    arabicDescription: 'قطع خبز مقرمشة، حمص مسلوق، لبن بالثوم، سمنة ساخنة ولحم مفروم مكسرات.',
  },
  {
    id: 'bk-falafel-plate',
    name: 'Falafel Plate (Breakfast)',
    arabicName: 'صحن فلافل فطور',
    price: 10,
    category: 'breakfast',
    description: 'Crispy herb-rich falafel golden-fried, accompanied by pickles and tahini dipping.',
    arabicDescription: 'صحن حبات فلافل طازجة مقرمشة مع مخللات وصلصة طحينة.',
    isVegetarian: true,
  },

  // --- SOUPS ---
  {
    id: 'soup-chicken-cream',
    name: 'Chicken Cream Soup',
    arabicName: 'شوربة كريمة الدجاج',
    price: 10,
    category: 'soups',
    description: 'Rich and velvety soup with shredded tender chicken and field mushrooms.',
    arabicDescription: 'شوربة غنية وكريمية مع قطع الدجاج الطرية.',
  },
  {
    id: 'soup-mushroom',
    name: 'Mushroom Cream Soup',
    arabicName: 'شوربة كريمة الفطر',
    price: 10,
    category: 'soups',
    description: 'Warm cream-infused soup packed with earth-rich brown and button mushrooms.',
    arabicDescription: 'شوربة الفطر الكريمية الساخنة والغنية بالنكهات.',
  },
  {
    id: 'soup-lentil',
    name: 'Lentil Soup',
    arabicName: 'شوربة عدس',
    price: 8,
    category: 'soups',
    description: 'Classic Levant yellow lentil soup, simmered with cumin and served with lemon and crispy bread.',
    arabicDescription: 'شوربة العدس الأصفر التقليدية مع الكمون تقدم مع الليمون والخبز المقرمش.',
    isVegetarian: true,
    isPopular: true,
  },
  {
    id: 'soup-veg',
    name: 'Vegetables Soup',
    arabicName: 'شوربة خضار',
    price: 8,
    category: 'soups',
    description: 'Light cleared broth loaded with seasonal diced carrots, celery, peas, and potatoes.',
    arabicDescription: 'حساء خفيف ومغذي بقطع خضار الموسم الطازجة.',
    isVegetarian: true,
  },

  // --- SALADS ---
  {
    id: 'salad-teboula',
    name: 'Teboula',
    arabicName: 'تبولة',
    price: 12,
    category: 'salads',
    description: 'Finely-chopped fresh parsley, mint, tomatoes, and bulgur, drizzled with lemon and olive oil.',
    arabicDescription: 'بقدونس مفروم ناعم، طماطم، نعناع، برغل، مع عصير ليمون وزيت زيتون.',
    isVegetarian: true,
    isPopular: true,
  },
  {
    id: 'salad-fetoush',
    name: 'Fetoush',
    arabicName: 'فتوش',
    price: 12,
    category: 'salads',
    description: 'Crispy mixed greens, radishes, tomatoes, and cucumber, topped with crunchy pita and sweet pomegranate dressing.',
    arabicDescription: 'سلطة خضار متنوعة مع قطع خبز محمص ودبس رمان حامض حلو.',
    isVegetarian: true,
  },
  {
    id: 'salad-oriental',
    name: 'Oriental Salad',
    arabicName: 'سلطة بلدية عربية',
    price: 10,
    category: 'salads',
    description: 'Standard local salad of cucumber, tomato, and parsley dressed in fresh lemon juice.',
    arabicDescription: 'الخيار والطماطم والبقدونس الطازج مع تتبيلة الليمون الفواح.',
    isVegetarian: true,
  },
  {
    id: 'salad-coleslaw',
    name: 'Coleslaw Salad',
    arabicName: 'كول سلو',
    price: 12,
    category: 'salads',
    description: 'Sweet shredded white cabbage and julienned carrots in a rich, velvety creamy dressing.',
    arabicDescription: 'ملفوف وجزر مبشور وممزوج بصلصتنا الكريمية الحلوة.',
    isVegetarian: true,
  },

  // --- APPETIZERS ---
  {
    id: 'app-grape-leaves',
    name: 'Grape Leaves (Appetizer plate)',
    arabicName: 'ورق عنب مقبلات',
    price: 15,
    category: 'appetizers',
    description: 'Fulfilling plate of chilled stuffed vine leaves with herbs, cooked patiently.',
    arabicDescription: 'صحن ممتد من ورق العنب البارد الشهي والمطبوخ بعناية.',
    isVegetarian: true,
  },
  {
    id: 'app-french-fries',
    name: 'French Fries',
    arabicName: 'بطاطس مقلية',
    price: 8,
    category: 'appetizers',
    description: 'Crispy and steaming classic fries, perfect for sharing.',
    arabicDescription: 'أصابع البطاطس المقلية الذهبية الشهية.',
    isVegetarian: true,
  },
  {
    id: 'app-spicy-potatoes',
    name: 'Spicy Potatoes (Batata Harra)',
    arabicName: 'بطاطا حرة مقبلات',
    price: 15,
    category: 'appetizers',
    description: 'Perfect shareable spicy potato skillet with garlic and generous coriander seasoning.',
    arabicDescription: 'صحن بطاطا حارة غني بالثوم والكزبرة والبهارات اللذيذة.',
    isSpicy: true,
  },
  {
    id: 'app-fried-egg',
    name: 'Fried Egg Plate (Appetizer)',
    arabicName: 'طبق بيض مقلي مقبلات',
    price: 10,
    category: 'appetizers',
    description: 'Simple egg plate seasoned with Mediterranean red pepper and sumac.',
    arabicDescription: 'طبق بيض مقلي كلاسيكي مع رشة سماق لفتح الشهية.',
  },
  {
    id: 'app-fried-egg-meat',
    name: 'Fried Egg with Meat (Appetizer)',
    arabicName: 'طبق بيض باللحم مقبلات',
    price: 18,
    category: 'appetizers',
    description: 'Fresh farm eggs sautéed with premium ground lamb bits.',
    arabicDescription: 'بيض مقلي طازج مع قطع لحم الغنم لتجربة دسمة.',
  },
  {
    id: 'app-fried-egg-cheese',
    name: 'Fried Egg with Cheese (Appetizer)',
    arabicName: 'طبق بيض بالجبنة مقبلات',
    price: 14,
    category: 'appetizers',
    description: 'Whipped eggs seasoned and slow-cooked with melting cheese blends.',
    arabicDescription: 'بيض مع خفقة من الأجبان البلدية المذابة اللذيذة.',
  },
  {
    id: 'app-chicken-liver',
    name: 'Chicken Liver Plate (Appetizer)',
    arabicName: 'صحن كبدة دجاج مقبلات',
    price: 25,
    category: 'appetizers',
    description: 'A larger portion of our tender skillet liver stewed in garlic, lemon, and rich spices.',
    arabicDescription: 'وجبة غنية من كبدة الدجاج المتبلة والمطبوخة بدبس الرمان والليمون.',
    isPopular: true,
  },
  {
    id: 'app-mixed-fried-veg',
    name: 'Mixed Fried Veg Plates (Appetizer)',
    arabicName: 'صحن خضار مقلي مشكل مقبلات',
    price: 20,
    category: 'appetizers',
    description: 'Sautéed eggplants, vegetable marrows, cauliflower served with flatbread.',
    arabicDescription: 'باذنجان، زهرة، بطاطا مقلية تقدم بشكل جميل مع الخبز وصلصات البداية.',
    isVegetarian: true,
  },
  {
    id: 'app-mufareka-egg',
    name: 'Mufareka Potato with Eggs (Appetizer)',
    arabicName: 'مفركة بطاطا بالبيض مقبلات',
    price: 15,
    category: 'appetizers',
    description: 'Comforting Levantine potato hash scrambled with whole eggs.',
    arabicDescription: 'مفركة البطاطا التقليدية بالبيض مع التوابل الشرقية.',
  },
  {
    id: 'app-mufareka-meat',
    name: 'Mufareka Potato with Meat (Appetizer)',
    arabicName: 'مفركة بطاطا باللحم مقبلات',
    price: 20,
    category: 'appetizers',
    description: 'Diced potatoes tossed with roasted minced meat flakes and pepper.',
    arabicDescription: 'قطع بطاطا محمرة مع خيوط لحم مفروم محمصة وبهارات.',
  },
  {
    id: 'app-fried-tomato',
    name: 'Fried Tomato (Appetizer)',
    arabicName: 'قلاية بندورة مقبلات',
    price: 15,
    category: 'appetizers',
    description: 'Stewed tomatoes under garlic olive oil.',
    arabicDescription: 'قلاية بندورة كلاسيكية مطبوخة بزيت الزيتون.',
    isVegetarian: true,
  },
  {
    id: 'app-fried-tomato-eggplant',
    name: 'Fried Tomato with Potato or Eggplant',
    arabicName: 'قلاية بندورة بالباذنجان أو البطاطا',
    price: 18,
    category: 'appetizers',
    description: 'Hearty fried tomato stew blended with toasted eggplants or crispy potato cubes.',
    arabicDescription: 'قلاية بندورة غنية مطبوخة بقطع بطاطا أو باذنجان مقلي.',
    isVegetarian: true,
  },
  {
    id: 'app-hummus',
    name: 'Hummus',
    arabicName: 'حمص بطحينة',
    price: 12,
    category: 'appetizers',
    description: 'Pureed chickpeas blended with rich sesame tahini, fresh lemon juice, garlic, topped with premium olive oil.',
    arabicDescription: 'حمص مخفوق بالطحينة والليمون وزيت الزيتون البكر.',
    isVegetarian: true,
    isPopular: true,
  },
  {
    id: 'app-beirut-hummus',
    name: 'Beirut Hummus',
    arabicName: 'حمص بيروتي',
    price: 14,
    category: 'appetizers',
    description: 'Creamy cream hummus mixed with garlic, spicy green pepper, and fresh finely chopped parsley.',
    arabicDescription: 'حمص على الطريقة البيروتية مع الثوم والبقدونس المفروم والفلفل الحار.',
    isVegetarian: true,
    isSpicy: true,
  },
  {
    id: 'app-hummus-meat',
    name: 'Hummus with Meat',
    arabicName: 'حمص باللحمة',
    price: 25,
    category: 'appetizers',
    description: 'Our silky classic hummus topped with warm sautéed minced lamb, pine nuts, and sizzling olive oil.',
    arabicDescription: 'صحن حمص ناهم مغطى بقطع لحم الغنم المقلية والصنوبر والسمنة.',
    isPopular: true,
  },
  {
    id: 'app-moutabal',
    name: 'Moutabal',
    arabicName: 'متبل باذنجان',
    price: 15,
    category: 'appetizers',
    description: 'Smoked grilled eggplant blended with tahini, lemon juice, yogurt, and pomegranate seeds.',
    arabicDescription: 'باذنجان مشوي على الفحم ومهروس مع الطحينة والليمون وزيت الزيتون.',
    isVegetarian: true,
  },
  {
    id: 'app-muhammara',
    name: 'Muhammara Plate',
    arabicName: 'صحن محمرة',
    price: 12,
    category: 'appetizers',
    description: 'Rich roasted red pepper paste blended with toasted walnuts, spices, breadcrumbs, and sweet pomegranate syrup.',
    arabicDescription: 'غموس الفلفل الأحمر المشوي مع الجوز ودبس الرمان والكمون.',
    isVegetarian: true,
    isSpicy: true,
  },
  {
    id: 'app-yogurt-cucumber',
    name: 'Yogurt with Cucumber',
    arabicName: 'سلطة خيار باللبن',
    price: 5,
    category: 'appetizers',
    description: 'Creamy chilled yogurt folded with sliced cucumbers, dried mint, and a touch of organic garlic.',
    arabicDescription: 'لبن زبادي بارد مع خيار مقطع ونعناع يابس لمسة ثوم.',
    isVegetarian: true,
  },
  {
    id: 'app-yogurt',
    name: 'Yogurt',
    arabicName: 'لبن زبادي',
    price: 5,
    category: 'appetizers',
    description: 'Chilled plain local yogurt bowl.',
    arabicDescription: 'صحن لبن زبادي طازج وبارد.',
    isVegetarian: true,
  },

  // --- AL AQSA SPECIALS ---
  {
    id: 'spec-broad-beans-oil',
    name: 'Broad Beans with Olive Oil (Special)',
    arabicName: 'فول بالزيت الأقصى المميز',
    price: 14,
    category: 'specials',
    description: 'Rich fava beans cooked to melting point with traditional family spices and cold press olive oil.',
    arabicDescription: 'فول مدمس مميز بالبهارات الخاصة وزيت زيتون بكر فخم.',
    isVegetarian: true,
  },
  {
    id: 'spec-broad-beans-tahineia',
    name: 'Broad Beans with Tahineia (Special)',
    arabicName: 'فول بالطحينة الأخصائي',
    price: 14,
    category: 'specials',
    description: 'Premium cooked fava beans dressed with deep and creamy sesame tahini marinade.',
    arabicDescription: 'فول مدمس بالخلطة السرية مع طحينة سميكة فاخرة.',
    isVegetarian: true,
  },
  {
    id: 'spec-meat-fatteh',
    name: 'Meat Fatteh (Special)',
    arabicName: 'فتة لحمة الأقصى الفاخرة',
    price: 30,
    category: 'specials',
    description: 'Premium Syrian-style fatteh with sizzling ghee, roasted almonds, and tender pulled meats.',
    arabicDescription: 'فتة الشامية التقليدية باللحمة والسمن الساخن والمكسرات المحمصة.',
    isPopular: true,
  },
  {
    id: 'spec-mousabaha',
    name: 'Mousabaha',
    arabicName: 'مسبحة بالخلطة',
    price: 12,
    category: 'specials',
    description: 'Warm whole cooked chickpeas blended cream-thick with raw tahini, lemon sauce, and green shatta chili.',
    arabicDescription: 'حمص مسلوق ساخن ممزوج مع طحينة سميكة وتتبيلة الليمون الحارة.',
    isVegetarian: true,
    isPopular: true,
  },
  {
    id: 'spec-falafel-plate',
    name: 'Falafel Plate (Special)',
    arabicName: 'صحن فلافل الأقصى المشكل',
    price: 10,
    category: 'specials',
    description: 'Extra light and crispy falafel spheres served with roasted chili dressing and pickles.',
    arabicDescription: 'فلافل ذهبية مع تتبيلة خاصة ومخللات مشكلة وطحينة دافئة.',
    isVegetarian: true,
  },
  {
    id: 'spec-potato-plate',
    name: 'Al Aqsa Potatoes Plate',
    arabicName: 'صحن بطاطا الأقصى الخاص',
    price: 15,
    category: 'specials',
    description: 'Crisp hand-cut potato wedges loaded with secret seasonings and served with garlic toum.',
    arabicDescription: 'صحن بطاطا مقطعة يدوياً محمرة بخلطة بهارات الأقصى السرية تقدم مع الثومية.',
    isPopular: true,
    isSpicy: true,
  },
  {
    id: 'spec-fatteh-ghee',
    name: 'Fatteh with Ghee',
    arabicName: 'فتة السمنة البلدية',
    price: 22,
    category: 'specials',
    description: 'Authentic toasted bread layers soaked in spiced chickpea juice, loaded with yogurt and drenched in hot local ghee.',
    arabicDescription: 'فتة شامية باللبن الغني المغطى بالسمن البلدي الحار والمكسرات.',
  },

  // --- AL AQSA GRILLED ---
  {
    id: 'grill-mixed-kilo',
    name: 'Mixed Grilled (1 KG)',
    arabicName: 'كيلو مشاوي مشكلة',
    price: 135,
    category: 'grilled',
    description: 'Ultimate charcoal-grilled feast: full combination of Shish Tawook, Tikka chunks, and Kabab skewers, with grilled vegetables and garlic paste.',
    arabicDescription: 'كيلو كامل من المشاوي المشكلة: أسياخ الكباب الشامي وشيش طاووق واللحم تيكا المشوي على الفحم مع الطماطم والبصل والثومية والخبز والبيواز.',
    isPopular: true,
  },
  {
    id: 'grill-mixed-plate',
    name: 'Mixed Grilled Plate',
    arabicName: 'صحن مشاوي مشكل',
    price: 42,
    category: 'grilled',
    description: 'An individual platter of mixed grills featuring lamb kebab, tikka, and shish tawook served with French fries and garlic dip.',
    arabicDescription: 'صحن مشاوي للأفراد غني باللحوم المختارة من الكباب وتيكا وشيش طاووق يقدم مع بطاطس وثومية.',
    isPopular: true,
  },
  {
    id: 'grill-shish-kilo',
    name: 'Shish Tawouq Charcoal-Grilled (1 KG)',
    arabicName: 'كيلو شيش طاووق على الفحم',
    price: 110,
    category: 'grilled',
    description: 'Full kilogram of fresh chicken breast cubes marinated in garlic, yogurt, and spices, flame-grilled on skewers.',
    arabicDescription: 'كيلو شيش طاووق دجاج مخلي متبل بالخلطة اللبنانية ومشوي بعناية.',
  },
  {
    id: 'grill-shish-plate',
    name: 'Shish Tawouq Plate',
    arabicName: 'صحن شيش طاووق',
    price: 28,
    category: 'grilled',
    description: 'Satisfying skewers of tender grilled marinated chicken breasts served with fries, garlic paste, and salad.',
    arabicDescription: 'صدر دجاج شيش طاووق مشوي على الفحم يقدم مع بطاطس وثوم ومخلل.',
  },
  {
    id: 'grill-tikka-kilo',
    name: 'Meat Tikka (1 KG)',
    arabicName: 'كيلو شقف تيكا لحم',
    price: 150,
    category: 'grilled',
    description: 'One kilogram of selected tender beef tenderloin chunks cubed, marinated in Syrian spices, and grilled of open embers.',
    arabicDescription: 'كيلو شقف تيكا غنم أو بقر بلدي متبل ومشوي على الفحم بشكل احترافي.',
  },
  {
    id: 'grill-tikka-plate',
    name: 'Meat Tikka Plate',
    arabicName: 'صحن شقف تيكا',
    price: 42,
    category: 'grilled',
    description: 'Robust plate of marinated beef tikka skewers served with parsley onion garnish, fries, and sauce.',
    arabicDescription: 'أشياخ شقف تيكا المحمرة على الجمر تقدم مع البطاطا المقلية وصلصة خاصة.',
  },
  {
    id: 'grill-kabab-kilo',
    name: 'Halabi Kabab (1 KG)',
    arabicName: 'كيلو كباب حلبي',
    price: 110,
    category: 'grilled',
    description: 'One kilogram of hand-ground minced lamb meat seasoned with parsley, onion, and Aleppo spices, grilled on charcoal.',
    arabicDescription: 'كيلو كباب حلبي غنم بلدي مفروم بالبقدونس والبصل والبهارات الحلبية.',
    isPopular: true,
  },
  {
    id: 'grill-kabab-plate',
    name: 'Halabi Kabab Plate',
    arabicName: 'صحن كباب حلبي',
    price: 30,
    category: 'grilled',
    description: 'Succulent skewers of minced meat kabab grilled on charcoal and served with flatbread and fries.',
    arabicDescription: 'صحن كباب لحم مشوي مشكل مع البصل والبقدونس وصلصة الغمس والخبز الساخن.',
  },
  {
    id: 'grill-arayes-kilo',
    name: 'Arayes (1 KG)',
    arabicName: 'كيلو عرايس لحم على الجمر',
    price: 100,
    category: 'grilled',
    description: 'Minced lamb spiced inside double-layered Arabic flatbread, toasted to a golden crisp over charcoal.',
    arabicDescription: 'كيلو خبز عرايس محشي باللحم المفروم المتبل والمشوي على الفحم ليصبح مقرمشاً.',
  },
  {
    id: 'grill-arayes-plate',
    name: 'Arayes Plate',
    arabicName: 'صحن عرايس لحم',
    price: 30,
    category: 'grilled',
    description: 'Four pieces of crispy baked flatbread filled with spiced minced meat, served with hummus and lemon wedges.',
    arabicDescription: 'صحن عرايس لحم من أربع قطع مقرمشة يقدم مع مخللات وشرائح ليمون.',
  },
  {
    id: 'grill-boneless-half',
    name: 'Half Grilled Boneless Chicken',
    arabicName: 'نصف دجاجة مسحبة على الفحم',
    price: 24,
    category: 'grilled',
    description: 'Juicy half chicken, fully boned, flattened and steeped in spicy yogurt marinade before charcoal grilling.',
    arabicDescription: 'نصف دجاجة مسحبة بالكامل متبلة بالليمون والبهارات ومطبوخة على الفحم.',
  },
  {
    id: 'grill-half-chicken',
    name: 'Half Grilled Chicken with Bone',
    arabicName: 'نصف دجاجة مشوية على الفحم بالعظم',
    price: 22,
    category: 'grilled',
    description: 'Golden charcoal-grilled fresh half chicken, crisp skin, moist interior, served with garlic paste.',
    arabicDescription: 'نصف دجاجة طازجة مشوية على الفحم تقدم مع خبز بالبيواز وثومية حارة.',
  },
  {
    id: 'grill-chicken-machine',
    name: 'Chicken Machine (Rotisserie)',
    arabicName: 'دجاجة شواية كاملة',
    price: 35,
    category: 'grilled',
    description: 'Full rotisserie chicken roasted slowly in our infrared machine until fat-rendered and crisp-skinned.',
    arabicDescription: 'دجاجة كاملة شواية تدور بالبهارات المميزة تقدم مع ثومية وبطاطس.',
  },
  {
    id: 'grill-chicken-machine-half',
    name: 'Half Chicken Machine (Rotisserie)',
    arabicName: 'نصف دجاجة شواية',
    price: 20,
    category: 'grilled',
    description: 'Half of our slow rotisserie roasted chicken served with pickles.',
    arabicDescription: 'نصف دجاجة شواية لذيذة مع التتبيلة والبطاطا الساخنة.',
  },
  {
    id: 'grill-veg-add',
    name: 'Grilled Tomatoes and Onions Side',
    arabicName: 'طماطم وبصل مشوي جانبي',
    price: 10,
    category: 'grilled',
    description: 'Skewers of whole ripe tomatoes and onions charred to caramel sweetness on charcoal.',
    arabicDescription: 'طماطم وبصل مشوي ومكرمل على الجمر.',
    isVegetarian: true,
  },

  // --- AL AQSA SANDWICHES ---
  {
    id: 'sand-tikka',
    name: 'Tikka Sandwich',
    arabicName: 'سندويش شقف تيكا',
    price: 16,
    category: 'sandwiches',
    description: 'Flame-grilled tender beef tikka chunks wrapped in fresh Arabic bread with onions, parsley, and light hummus spread.',
    arabicDescription: 'قطع لحم تيكا مشوية مع البيواز والحمص ملفوفة بخبز طازج.',
  },
  {
    id: 'sand-kabab',
    name: 'Kabab Sandwich',
    arabicName: 'سندويش كباب حلبي',
    price: 14,
    category: 'sandwiches',
    description: 'Juicy skewer of spiced minced lamb wrapped with onions, sumac, fresh parsley, and tomato slices.',
    arabicDescription: 'سيخ كباب لحم غنم مشوي مع رشة سماق وبصل وبندورة.',
  },
  {
    id: 'sand-shish',
    name: 'Shish Tawouq Sandwich',
    arabicName: 'سندويش شيش طاووق',
    price: 14,
    category: 'sandwiches',
    description: 'Grilled chicken breast cubes wrapped in Lebanese flatbread with shredded lettuce, French fries, and our strong garlic toum.',
    arabicDescription: 'شيش طاووق دجاج مع بطاطا مقلية وثومية ومخلل خيار.',
    isPopular: true,
  },
  {
    id: 'sand-falafel',
    name: 'Falafel Sandwich',
    arabicName: 'سندويش فلافل عادي',
    price: 5,
    category: 'sandwiches',
    secondaryPrice: [
      { label: 'Small / صغير', price: 5 },
      { label: 'Large / كبير', price: 10 },
    ],
    description: 'Crisp falafels crushed with chopped tomato, cucumber, mint, and a rich ribbon of tahini sauce.',
    arabicDescription: 'حبات فلافل مقرمشة مع الخضار المشكلة والطحينة الفواحة.',
    isVegetarian: true,
  },
  {
    id: 'sand-falafel-mix',
    name: 'Mixed Falafel Sandwich (With Eggplant / Fried Potatoes)',
    arabicName: 'سندويش فلافل مشكل خضار',
    price: 7,
    category: 'sandwiches',
    secondaryPrice: [
      { label: 'Small / صغير', price: 7 },
      { label: 'Large / كبير', price: 12 },
    ],
    description: 'Crispy falafels wrapped together with golden fried eggplant, potato wedges, fresh herbs, and tahini splash.',
    arabicDescription: 'سندويتش فلافل على الأصول مع باذنجان وبطاطا مقلية وطحينة.',
    isVegetarian: true,
    isPopular: true,
  },
  {
    id: 'sand-falafel-foul',
    name: 'Falafel Sandwich with Foul or Hummus',
    arabicName: 'سندويش فلافل بالفول أو الحمص',
    price: 6,
    category: 'sandwiches',
    secondaryPrice: [
      { label: 'Small / صغير', price: 6 },
      { label: 'Large / كبير', price: 11 },
    ],
    description: 'Creative local wrap blending hot falafels with mashed warm creamy hummus or seasoned fava beans (foul).',
    arabicDescription: 'سندويش فلافل محشو يضاف إليه حمص كريمي أو فول مدمس طازج.',
    isVegetarian: true,
  },
  {
    id: 'sand-hummus-meat',
    name: 'Hummus with Meat Sandwich',
    arabicName: 'سندويش حمص باللحم',
    price: 14,
    category: 'sandwiches',
    description: 'Rich spreading of classical hummus loaded inside flatbread with freshly sautéed minced meat chunks.',
    arabicDescription: 'حمص ناعم مع لحم مفروم مشوي دافئ ملفوف بخبز بلدي.',
  },
  {
    id: 'sand-burger-beef',
    name: 'Beef Burger',
    arabicName: 'برجر لحم بقري',
    price: 10,
    category: 'sandwiches',
    secondaryPrice: [
      { label: 'Normal / عادي', price: 10 },
      { label: 'Special / سوبر خاص', price: 15 },
    ],
    description: 'Grilled minced beef patty with lettuce, tomatoes, mayonnaise and ketchup in a soft sesame bun.',
    arabicDescription: 'برجر لحم كلاسيكي مشوي مع الخس والطماطم والصلصات السهلة.',
  },
  {
    id: 'sand-burger-chk',
    name: 'Chicken Burger',
    arabicName: 'برجر دجاج مقرمش',
    price: 8,
    category: 'sandwiches',
    secondaryPrice: [
      { label: 'Normal / عادي', price: 8 },
      { label: 'Special / سوبر خاص', price: 12 },
    ],
    description: 'Crispy pan-fried or grilled chicken breast patty with melting mayo and crunchy lettuce shreds.',
    arabicDescription: 'برجر دجاج شهي مقرمش أو مشوي مع المايونيز والخس في خبز السمسم.',
  },
  {
    id: 'sand-burger-beef-egg',
    name: 'Beef Burger with Egg',
    arabicName: 'برجر لحم بالبيض',
    price: 12,
    category: 'sandwiches',
    secondaryPrice: [
      { label: 'Normal / عادي', price: 12 },
      { label: 'Special / سوبر خاص', price: 17 },
    ],
    description: 'Satisfying double deck beef burger topped with a sunny pan-fried egg and cheddar slice.',
    arabicDescription: 'برجر لحم مغذى مع حبة بيض مقلي غنية وجبن ذائب.',
  },
  {
    id: 'sand-burger-chk-egg',
    name: 'Chicken Burger with Egg',
    arabicName: 'برجر دجاج بالبيض',
    price: 10,
    category: 'sandwiches',
    secondaryPrice: [
      { label: 'Normal / عادي', price: 10 },
      { label: 'Special / سوبر خاص', price: 14 },
    ],
    description: 'Tender chicken patty combined with a freshly cooked egg in a soft bun.',
    arabicDescription: 'برجر دجاج مع البيض المقلي الساخن.',
  },

  // --- AL AQSA SHAWARMA ---
  {
    id: 'sha-meat-sm',
    name: 'Small Meat Shawarma',
    arabicName: 'شاورما لحم صغير',
    price: 7,
    category: 'shawarma',
    description: 'Traditional spiced beef & lamb slivers shaved off vertically rotisserie, wrapped with pickles, onion, sumac, and sesame tahini.',
    arabicDescription: 'لفافة شاورما اللحم متبلة بالبهارات الشامية مع البيواز والطحينة والمخلل.',
  },
  {
    id: 'sha-meat-lg',
    name: 'Large Meat Shawarma',
    arabicName: 'شاورما لحم كبير',
    price: 13,
    category: 'shawarma',
    description: 'A larger, thicker roll of vertically-carved spiced beef shawarma wrapped in freshly baked saj bread.',
    arabicDescription: 'شاورما لحم في خبز الصاج الكبير الغني بالطحينة ومخلل الثوم.',
    isPopular: true,
  },
  {
    id: 'sha-chk-sm',
    name: 'Small Chicken Shawarma',
    arabicName: 'شاورما دجاج صغير',
    price: 6,
    category: 'shawarma',
    description: 'Rotating rotisserie chicken shavings bundled with golden French fry pieces, cucumber pickles, and garlic paste.',
    arabicDescription: 'شاورما دجاج صغيرة على الأصول مع الثومية ومخلل الخيار.',
  },
  {
    id: 'sha-chk-lg',
    name: 'Large Chicken Shawarma',
    arabicName: 'شاورما دجاج كبير',
    price: 11,
    category: 'shawarma',
    description: 'Thick chicken shawarma wrap in warm markook/saj bread loaded with garlic whip and potatoes.',
    arabicDescription: 'شاورما دجاج حجم كبير غنية بالثوم والبطاطا المقرمشة ومغلفة بخبز الصاج.',
    isPopular: true,
  },
  {
    id: 'sha-meal-meat',
    name: 'Meat Shawarma Arabic Meal',
    arabicName: 'وجبة شاورما لحم عربي',
    price: 22,
    category: 'shawarma',
    description: 'Sliced large meat shawarma roll served on a tray with French fries, salad greens, tahini dipping, pickles, and crisp flatbread.',
    arabicDescription: 'وجبة شاورما لحم مقطعة فرنسي تقدم مع بطاطس مقلية وطحينة ومخللات.',
  },
  {
    id: 'sha-meal-chk',
    name: 'Chicken Shawarma Arabic Meal',
    arabicName: 'وجبة شاورما دجاج عربي',
    price: 20,
    category: 'shawarma',
    description: 'Finely sliced chicken wraps served with crispy fries, premium garlic toum sauce container, and pickled vegetables.',
    arabicDescription: 'وجبة شاورما دجاج مقطعة عربي تقدم على صينية خشبية مع بطاطا مقلية وثومية ومخلل.',
    isPopular: true,
  },
  {
    id: 'sha-plate-meat-hum',
    name: 'Meat Shawarma Plate with Hummus',
    arabicName: 'صحن شاورما لحم بالحمص',
    price: 32,
    category: 'shawarma',
    description: 'Savory strips of roasted beef shawarma served on top of a full hummus bowl, dressed with spices and olive oil.',
    arabicDescription: 'صحن من حمصنا الحريري مغطى بجبل من شاورما اللحم المشوي اللذيذ مع الخبز والليمون.',
  },
  {
    id: 'sha-plate-chk-hum',
    name: 'Chicken Shawarma Plate with Hummus',
    arabicName: 'صحن شاورما دجاج بالحمص',
    price: 30,
    category: 'shawarma',
    description: 'Our smooth garlic-infused hummus beautifully paired with freshly shaved chicken shawarma skewers.',
    arabicDescription: 'حمص الأقصر الشهير مزين بشرائح شاورما الدجاج الذهبية والثومية وزيت الزيتون.',
  },
  {
    id: 'sha-mini-12',
    name: 'Mini Shawarma Box (12 Pieces Mix)',
    arabicName: 'علبة ميني شاورما (12 قطعة مشكل)',
    price: 35,
    category: 'shawarma',
    description: 'Perfect for sharing! Platter of 12 bite-sized mini shawarmas (half chicken, half meat) served with a duo of garlic sauce and tahini.',
    arabicDescription: 'صندوق المشاركة السعيد! 12 قطعة ميني شاورما مشكلة بين اللحم والدجاج تقدم مع ثومية وطحينة وبطاطس.',
    isPopular: true,
  },

  // --- AL AQSA PASTRIES ---
  {
    id: 'pys-mohemara-manakeesh',
    name: 'Mohemara Manakeesh',
    arabicName: 'منقوشة محمرة',
    price: 7,
    category: 'pastries',
    description: 'Soft home-kneaded sourdough flatbread topped with rich spicy Syrian roasted red bell pepper and onion seed paste.',
    arabicDescription: 'عجينة منقوشة هشة مخبوزة بصلصة المحمرة الحارة مع حبوب البركة.',
    isSpicy: true,
  },
  {
    id: 'pys-cheese-manakeesh',
    name: 'Cheese Manakeesh',
    arabicName: 'منقوشة جبنة عكاوي',
    price: 8,
    category: 'pastries',
    description: 'Brimming with fresh-salted traditional Akkawi/Nabulsi cheeses, melted in our stone oven.',
    arabicDescription: 'منقوشة غنية بخليط من الأجبان البلدية الذائبة واللذيذة.',
    isPopular: true,
  },
  {
    id: 'pys-zaater-manakeesh',
    name: 'Zaater Manakeesh',
    arabicName: 'منقوشة زعتر بالزيت',
    price: 7,
    category: 'pastries',
    description: 'Traditional wild thyme thyme herb mixture blended with premium olive oil, baked aromatic.',
    arabicDescription: 'خلطة الزعتر البلدي الفواحة مع زيت الزيتون البكر المخبوزة في الفرن الحجري.',
  },
  {
    id: 'pys-labna-manakeesh',
    name: 'Labna Manakeesh',
    arabicName: 'منقوشة لبنة بلدية',
    price: 8,
    category: 'pastries',
    description: 'Thick, creamy and tangly Mediterranean strained yogurt spread warm on flatbread.',
    arabicDescription: 'لبنة بلدية طازجة ممتازة ممدودة على عجينة منقوشة ساخنة.',
  },
  {
    id: 'pys-spinach-manakeesh',
    name: 'Spinach Manakeesh',
    arabicName: 'منقوشة سبانخ بالبلدي',
    price: 8,
    category: 'pastries',
    description: 'Fresh chopped spinach leaves spiced with sour sumac, lemon juice, diced onions, and olive oil.',
    arabicDescription: 'سبانخ طازجة متبلة بالسماق الحامض والليمون وبصل خفيف ممدودة بالفرن.',
    isVegetarian: true,
  },
  {
    id: 'pys-meat-tomato-manakeesh',
    name: 'Meat with Tomato Manakeesh',
    arabicName: 'منقوشة لحمة بالبندورة',
    price: 8,
    category: 'pastries',
    description: 'Damascene style finely ground meat roasted into flatbread with finely mashed tomatoes and spices.',
    arabicDescription: 'لحم مفروم مطبوخ مع بصل وطماطم مفرومة على عجين رقيق.',
  },
  {
    id: 'pys-potato-manakeesh',
    name: 'Potato Manakeesh',
    arabicName: 'منقوشة بطاطا بالبهار',
    price: 8,
    category: 'pastries',
    description: 'Seasoned potato paste spiced with cumin and herbs layered on flatbread.',
    arabicDescription: 'حشوة بطاطا مهروسة متبلة ومخبوزة بشكل رائع.',
  },
  {
    id: 'pys-meat-cheese-manakeesh',
    name: 'Meat with Cheese Manakeesh',
    arabicName: 'منقوشة لحم بالجبن',
    price: 10,
    category: 'pastries',
    description: 'Sautéed spiced minced meat directly baked under a layer of melting local cheeses.',
    arabicDescription: 'مزيج فاخر من اللحم المفروم المتبل مع طبقة غنية من الجبنة البلدية الذائبة.',
    isPopular: true,
  },
  {
    id: 'pys-mohemara-cheese-manakeesh',
    name: 'Mohemara with Cheese Manakeesh',
    arabicName: 'منقوشة محمرة بالجبنة',
    price: 10,
    category: 'pastries',
    description: 'Tangy red pepper paste married with stretchy Akawi mozzarella blend.',
    arabicDescription: 'صلصة المحمرة المتبلة الحارة مغطاة بطبقة غنية من الجبن.',
    isSpicy: true,
  },
  {
    id: 'pys-zaater-cheese-manakeesh',
    name: 'Zaater with Cheese Manakeesh',
    arabicName: 'منقوشة زعتر وجبنة',
    price: 10,
    category: 'pastries',
    description: 'Beautiful double flavor profile: half wild thyme, half melting Arabic white cheese.',
    arabicDescription: 'مزيج رائع يجمع بين نكهة الزعتر اللذيذة والجبنة الذائبة الساخنة.',
  },
  {
    id: 'pys-labna-zaater-manakeesh',
    name: 'Labna with Zaater Manakeesh',
    arabicName: 'منقوشة لبنة بالزعتر',
    price: 10,
    category: 'pastries',
    description: 'Cool tangy labneh base dressed with generous aromatic green zaatar powder and olive oil.',
    arabicDescription: 'لبنة كريمية باردة منثور عليها الزعتر الأخضر الغني بالسمسم.',
  },
  {
    id: 'pys-egg-cheese-manakeesh',
    name: 'Egg with Cheese Manakeesh',
    arabicName: 'منقوشة بيض بالجبن',
    price: 10,
    category: 'pastries',
    description: 'Fresh cracked scrambled egg fully loaded and baked alongside Akawi white cheese.',
    arabicDescription: 'بيض مخفوق ومخبوز مباشرة مع مكس الجبنة الغني.',
  },
  {
    id: 'pys-egg-meat-manakeesh',
    name: 'Egg with Meat Manakeesh',
    arabicName: 'منقوشة بيض باللحمة',
    price: 10,
    category: 'pastries',
    description: 'Hearty baked flatbread loaded with eggs and spiced minced meat flakes.',
    arabicDescription: 'بيض مخفوق مخبوز مع اللحم المفروم المتبل.',
  },
  {
    id: 'pys-kafta-manakeesh',
    name: 'Kafta Manakeesh',
    arabicName: 'منقوشة لحم كفتة بالبهار',
    price: 12,
    category: 'pastries',
    description: 'Ground beef and lamb seasoned with onion, parsley, and kafta spices, baked thin.',
    arabicDescription: 'لحم كفتة متبل بالبصل والقدونس والبهارات ممدود رقيق في الفرن.',
  },
  {
    id: 'pys-sojuck-cheese-manakeesh',
    name: 'Sojuck with Cheese Manakeesh',
    arabicName: 'منقوشة سجق بالجبنة',
    price: 12,
    category: 'pastries',
    description: 'Garlic-spiced beef cured sausage slices baked on flatbread under cheese topping.',
    arabicDescription: 'منقوشة قطع السجق الأرمني الحار مع الثوم والبهارات والجبن الذائب.',
    isSpicy: true,
  },

  // --- PIZZAS (Under Pastries Category in prompt but nice sub-header/filter) ---
  {
    id: 'piz-margherita',
    name: 'Margherita Pizza',
    arabicName: 'بيتزا مارغريتا',
    price: 20,
    category: 'pastries',
    description: 'Our house-made Italian pizza sauce, rich layer of mozzarella cheese, olive oil, and fresh oregano herbs.',
    arabicDescription: 'صلصة الطماطم الغنية مع طبقة سميكة من جبن الموتزاريلا والزعتر البري.',
    isVegetarian: true,
  },
  {
    id: 'piz-veg',
    name: 'Vegetables Pizza',
    arabicName: 'بيتزا الخضار المشكلة',
    price: 22,
    category: 'pastries',
    description: 'Sauce and cheese topped with black olives, green bell peppers, field mushrooms, onions, and sweet corn.',
    arabicDescription: 'بيتزا غنية بقطع الفطر والفلفل الأخضر والذرة والزيتون الأسود والبصل.',
    isVegetarian: true,
  },
  {
    id: 'piz-chk',
    name: 'Chicken Pizza',
    arabicName: 'بيتزا الدجاج والزيتون',
    price: 25,
    category: 'pastries',
    description: 'Charcoal shredded chicken breast, bell peppers, mozzarella, and special white baseline sauce.',
    arabicDescription: 'بيتزا مغطاة بقطع دجاج مشوية مع الموتزاريلا والفلفل الحلو والزيتون.',
  },
  {
    id: 'piz-meat',
    name: 'Meat Pizza',
    arabicName: 'بيتزا اللحم المتبل',
    price: 30,
    category: 'pastries',
    description: 'Load of savory minced ground meat, pepperoni, peppers, onions, and thick melted cheeses.',
    arabicDescription: 'بيتزا دسمة بقطع اللحم المفروم الغني والبهارات والبصل وجبن الموتزاريلا.',
    isPopular: true,
  },

  // --- AL AQSA PLATES ---
  {
    id: 'plt-kafta-tomato',
    name: 'Kafta with Tomato Plate',
    arabicName: 'صحن كفتة بالبندورة في الفرن',
    price: 30,
    category: 'plates',
    description: 'Ground seasoned lamb baked in a casserole with sliced tomatoes, potatoes, onions, and red garlic tomato broth.',
    arabicDescription: 'صينية كفتة اللحم متبلة بالقدونس والبصل ومطبوخة بالفرن مع البندورة والبطاطس.',
    isPopular: true,
  },
  {
    id: 'plt-kafta-tahineia',
    name: 'Kafta with Tahineia Plate',
    arabicName: 'صحن كفتة بالطحينة في الفرن',
    price: 30,
    category: 'plates',
    description: 'Kafta skewers baked in a clay tray with thick and tangy warm sesame tahini cream, onion, and lemon.',
    arabicDescription: 'كفتة اللحم المفروم المشوي والمطبوخ في الفرن بصلصة الطحينة والليمون الحامضة الحلوة والمزينة بالمكسرات.',
    isPopular: true,
  },
  {
    id: 'plt-chk-nashef',
    name: 'Chicken Nashef Plate',
    arabicName: 'صحن ناشف دجاج بالثوم والبهار',
    price: 25,
    category: 'plates',
    description: 'Succulent cubes of chicken pan-fried thick with sweet bell peppers, onions, tomatoes, and UAE spices.',
    arabicDescription: 'قطع الدجاج المقلية الجافة مع البصل والفلفل الملون وتتبيلتنا الشامية والخليجية.',
  },
  {
    id: 'plt-beef-nashef',
    name: 'Beef Nashef Plate',
    arabicName: 'صحن ناشف لحم بقري بلدي',
    price: 30,
    category: 'plates',
    description: 'Beef strips pan-seared dry-hot with sweet capsicum, coriander seeds, and caramelized onions.',
    arabicDescription: 'شرائح اللحم البقري المحمرة جاف في الليمون والثوم والفلفل والبصل.',
  },
  {
    id: 'plt-chk-biryani',
    name: 'Chicken Biryani Plate',
    arabicName: 'صحن برياني دجاج على الأصول',
    price: 22,
    category: 'plates',
    description: 'Fragrant basmati rice cooked with authentic biryani masala and served with soft saffron roasted quarter chicken.',
    arabicDescription: 'أرز بسمتي هندي طويل الحبة مطبوخ ببهارات البرياني الهندية يقدم مع دجاج بالزعفران.',
    isPopular: true,
  },
  {
    id: 'plt-today-chk',
    name: 'Today’s Dish (Chicken Special)',
    arabicName: 'طبق اليوم (دجاج مميز)',
    price: 25,
    category: 'plates',
    description: 'Our traditional home-style Arabic chicken dish changing daily (e.g. Molokhia, Kabsa, or Maqluba), served with rice.',
    arabicDescription: 'صناعة منزلية دافئة تتغير يومياً (ملوخية، كبسة، مقلوبة دجاج) تقدم مع أرز طويل الحبة.',
  },
  {
    id: 'plt-today-meat',
    name: 'Today’s Dish (Meat Special)',
    arabicName: 'طبق اليوم (لحم فاخر)',
    price: 30,
    category: 'plates',
    description: 'An authentic feast of the day (e.g. Mansaf, Ouzi, or Shakriyeh) featuring tender slowly-simmered beef or lamb.',
    arabicDescription: 'طبق مطبوخ ببطء للحصول على طراوة كاملة (منسف أردني، أوزي، شاكرية لحم) يقدم كول ليلة.',
  },

  // --- COLD BEVERAGES ---
  {
    id: 'bev-water-lg',
    name: 'Mineral Water (Big)',
    arabicName: 'مياه معدنية حجم كبير',
    price: 4,
    category: 'beverages',
    description: 'Chilled local pure spring water glass or bottle (Large-size).',
    arabicDescription: 'مباه صحية باردة سعة لتر ونصف.',
  },
  {
    id: 'bev-water-sm',
    name: 'Mineral Water (Small)',
    arabicName: 'مياه معدنية حجم صغير',
    price: 2,
    category: 'beverages',
    description: 'Small chilled pure spring water pouch or bottle.',
    arabicDescription: 'مياه صحية صغيرة باردة.',
  },
  {
    id: 'bev-soda',
    name: 'Soft Drinks (Coca-Cola / Pepsi / Sprite / Fanta)',
    arabicName: 'مشروبات غازية متنوعة',
    price: 3,
    category: 'beverages',
    description: 'Your choice of ice-cold carbonated mineral soda cans.',
    arabicDescription: 'كوكاكولا، بيبسي، سبرايت، فانتا علب باردة ومثلجة.',
  },
  {
    id: 'bev-eran',
    name: 'Eran Milk (Ayran Yogurt Drink)',
    arabicName: 'لبن عيران بلدي بارد',
    price: 6,
    category: 'beverages',
    description: 'Traditional refreshing Middle Eastern salted yogurt milk drink blended with dried mint shreds.',
    arabicDescription: 'شراب اللبن الزبادي التقليدي المملح والمثلج مع لمسة نعناع منعشة.',
    isPopular: true,
  },
  {
    id: 'bev-lemon-mint',
    name: 'Lemon with Mint Juice',
    arabicName: 'عصير ليمون بالنعناع طازج',
    price: 8,
    category: 'beverages',
    description: 'Freshly squeezed lemon juice cold-blended to order with fresh green mint leaves and ice crush.',
    arabicDescription: 'ليمون حامض معصر طازج ومخفوق بالخلاط مع حبات النعناع الأخضر والثلج المبشور.',
    isPopular: true,
  },
  {
    id: 'bev-orange',
    name: 'Fresh Orange Juice',
    arabicName: 'عصير برتقال طازج مصفى',
    price: 8,
    category: 'beverages',
    description: 'Pure 100% natural cold pressed sweet Valencia oranges, high in vitamin C, with no added sugar.',
    arabicDescription: 'عصير برتقال طبيعي معصور على البارد حلو ومنعش بدون سكر مضاف.',
  },
];

export const GOOGLE_REVIEWS = [
  {
    name: 'Samir Al-Mansoori',
    rating: 5,
    comment: 'The mixed grilled kilo is phenomenal! Excellent value and very clean shop in Warsan. Shawarma mini box is highly recommended for family gatherings.',
    date: '3 weeks ago',
  },
  {
    name: 'Jessica Thompson',
    rating: 5,
    comment: 'Authentic taste. The falafel sandwich with eggplant is only 7 AED and it is huge and delicious. The garlic toum paste is very strong and tasty. Will order again on WhatsApp.',
    date: '1 month ago',
  },
  {
    name: 'Zaheer Khan',
    rating: 4,
    comment: 'Very tasty plates. Love their Kafta with Tahina cooked in oven, extremely juicy. Good fast delivery to International City Phase 2.',
    date: '2 months ago',
  },
];
